export const dynamic='force-dynamic';
export const maxDuration=60;
const START=100,FEE=.0002,SLIPPAGE=.0002,DAY=86400000,BASE='https://api.binance.us/api/v3';
const WINNERS=[
{symbol:'ZECUSD',minutes:15,lookback:8,confirm:.0015,minProfit:.0015,stop:.02,cooldown:1},
{symbol:'LINKUSD',minutes:30,lookback:5,confirm:.0015,minProfit:.0015,stop:.02,cooldown:1},
{symbol:'ETHUSD',minutes:15,lookback:3,confirm:.003,minProfit:.0015,stop:.02,cooldown:1},
{symbol:'PEPEUSD',minutes:15,lookback:5,confirm:.0015,minProfit:.0015,stop:.02,cooldown:1},
{symbol:'AVAXUSD',minutes:30,lookback:5,confirm:.005,minProfit:.0015,stop:.02,cooldown:1}
];
async function getJson(url){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok){const t=await r.text().catch(()=> '');throw new Error(`Binance.US ${r.status}${t?`: ${t.slice(0,100)}`:''}`)}return r.json()}
async function candles(symbol,days=90){const end=Date.now(),start=end-days*DAY,out=[];let cursor=start;while(cursor<end){const rows=await getJson(`${BASE}/klines?symbol=${encodeURIComponent(symbol)}&interval=15m&startTime=${cursor}&endTime=${end}&limit=1000`);if(!rows?.length)break;for(const r of rows)out.push({time:+r[0],open:+r[1],high:+r[2],low:+r[3],close:+r[4],volume:+r[5]});const next=+rows[rows.length-1][0]+900000;if(next<=cursor)break;cursor=next;if(rows.length<1000)break}const m=new Map();out.forEach(c=>m.set(c.time,c));return [...m.values()].filter(c=>c.time>=start&&c.time<=end).sort((a,b)=>a.time-b.time)}
function aggregate(cs,minutes){if(minutes===15)return cs;const size=minutes*60000,g=new Map();for(const c of cs){const k=Math.floor(c.time/size)*size,x=g.get(k);if(!x)g.set(k,{...c,time:k});else{x.high=Math.max(x.high,c.high);x.low=Math.min(x.low,c.low);x.close=c.close;x.volume+=c.volume}}return [...g.values()].sort((a,b)=>a.time-b.time)}
function simulate(cs,cfg){let cash=START,units=0,pos='CASH',entry=0,fees=0,trades=0,wins=0,losses=0,peak=START,dd=0,entryCapital=0,cooldown=0;for(let i=Math.max(3,cfg.lookback);i<cs.length;i++){const c=cs[i],prev=cs[i-1];if(cooldown>0)cooldown--;const recent=cs.slice(i-cfg.lookback,i),lo=Math.min(...recent.map(x=>x.low)),hi=Math.max(...recent.map(x=>x.high)),fell=recent[0].close>recent.at(-1).close,rose=recent[0].close<recent.at(-1).close,rebound=c.close/lo-1,pullback=c.close/hi-1,higherLow=c.low>lo&&c.close>prev.high,lowerHigh=c.high<hi&&c.close<prev.low,buy=pos==='CASH'&&cooldown===0&&fell&&higherLow&&rebound>=cfg.confirm,ret=pos==='COIN'?c.close/entry-1:0,stop=pos==='COIN'&&ret<=-cfg.stop,sell=pos==='COIN'&&rose&&lowerHigh&&pullback<=-cfg.confirm&&ret>=cfg.minProfit;if(buy){entryCapital=cash;const execution=c.close*(1+SLIPPAGE),fee=cash*FEE;units=(cash-fee)/execution;fees+=fee;cash=0;entry=c.close;pos='COIN';trades++}else if(pos==='COIN'&&(sell||stop)){const execution=c.close*(1-SLIPPAGE),gross=units*execution,fee=gross*FEE;cash=gross-fee;fees+=fee;units=0;trades++;if(cash>entryCapital)wins++;else losses++;pos='CASH';entry=0;entryCapital=0;cooldown=cfg.cooldown}const eq=cash+units*c.close;if(eq>peak)peak=eq;dd=Math.max(dd,(peak-eq)/peak)}const ending=cash+units*cs.at(-1).close,cycles=wins+losses;return{endingBalance:ending,returnPct:(ending/START-1)*100,trades,fees,winRate:cycles?wins/cycles*100:0,maxDrawdown:dd*100}}
export async function GET(){try{const results=[];for(const cfg of WINNERS){try{const raw=await candles(cfg.symbol,90);if(raw.length<7000)throw new Error(`Only ${raw.length} candles`);const bars=aggregate(raw,cfg.minutes),bot=simulate(bars,cfg),hold=START*raw.at(-1).close/raw[0].close;results.push({...cfg,candles:raw.length,...bot,buyHoldEnding:hold,buyHoldReturnPct:(hold/START-1)*100,excessVsHold:bot.endingBalance-hold,beatHold:bot.endingBalance>hold})}catch(e){results.push({...cfg,error:e.message})}}const valid=results.filter(x=>!x.error).sort((a,b)=>b.endingBalance-a.endingBalance);return Response.json({days:90,startBalance:START,feeRate:FEE,slippageRate:SLIPPAGE,frozen:true,marketsTested:valid.length,profitableCount:valid.filter(x=>x.endingBalance>START).length,beatHoldCount:valid.filter(x=>x.beatHold).length,best:valid[0]||null,results:valid,errors:results.filter(x=>x.error)})}catch(e){return Response.json({error:e.message},{status:502})}}
