'use client';
import {useState} from 'react';
export default function MonthTest(){
 const [data,setData]=useState(null),[status,setStatus]=useState('idle'),[error,setError]=useState('');
 async function run(){setStatus('loading');setError('');try{const r=await fetch('/api/month-test',{cache:'no-store'});const text=await r.text();let d;try{d=JSON.parse(text);}catch{throw new Error(text?.slice(0,180)||`Server returned ${r.status}`);}if(!r.ok||d.error)throw new Error(d.error||'30 day test failed');setData(d);setStatus('done');}catch(e){setError(e.message||'30 day test failed');setStatus('error');}}
 return <main><header><div><span className="eyebrow">OUT OF SAMPLE TEST</span><h1>30 Day BTC Championship</h1><p>Test the strongest seven day strategies across the last 30 days without reoptimizing them.</p></div><a className="live" href="/optimizer">Back to optimizer</a></header>
 <section className="panel" style={{marginTop:32}}><div className="panelHead"><div><span className="eyebrow">$100 START</span><h2>Do the winners survive a month?</h2></div><button onClick={run} disabled={status==='loading'}>{status==='loading'?'Downloading 30 days...':data?'Run again':'Run 30 day test'}</button></div>
 <p className="panelCopy">This does not search for new settings. It freezes several of the strongest seven day configurations and tests them on a longer 30 day window with the same simulated 0.6% transaction fee.</p>
 {status==='idle'&&<div className="empty">Press Run 30 day test. The server now downloads 15 minute BTC history directly and aggregates it to 30 minute candles where needed, which is much faster than fetching every one minute candle.</div>}
 {status==='loading'&&<div className="empty">Downloading 30 days of 15 minute BTC candles and replaying the frozen strategies. Rate limit retries are automatic.</div>}
 {status==='error'&&<div className="empty errorText">30 day test could not finish: {error}</div>}
 {data&&<><div className="benchmarkRow"><Metric label="15 MINUTE CANDLES" value={data.candles.toLocaleString()}/><Metric label="BUY AND HOLD" value={`$${data.buyHoldEnding.toFixed(2)}`}/><Metric label="HOLD RETURN" value={`${data.buyHoldReturnPct>=0?'+':''}${data.buyHoldReturnPct.toFixed(2)}%`}/></div>
 <div className="backtestSummary"><strong>Best 30 day bot: {data.best.name} at ${data.best.endingBalance.toFixed(2)}</strong><span>{data.best.endingBalance>data.buyHoldEnding?'It beat buy and hold in this 30 day window.':'Buy and hold still beat the best tested bot in this 30 day window.'}</span></div>
 <div className="rankList">{data.results.map((s,i)=><div className={`rankRow ${s.endingBalance>data.buyHoldEnding?'beatHold':''}`} key={s.name}><div className="rankNum">#{i+1}</div><div className="rankName"><strong>{s.name}: {s.minutes} minute EMA {s.fast}/{s.slow}</strong><span>Confirm {(s.confirm*100).toFixed(2)}%, min profit {(s.minProfit*100).toFixed(2)}%, stop {(s.stop*100).toFixed(2)}%.</span></div><RM label="ENDING" value={`$${s.endingBalance.toFixed(2)}`}/><RM label="RETURN" value={`${s.returnPct>=0?'+':''}${s.returnPct.toFixed(2)}%`}/><RM label="TRADES" value={String(s.trades)}/><RM label="FEES" value={`$${s.fees.toFixed(2)}`}/><RM label="WIN RATE" value={`${s.winRate.toFixed(1)}%`}/><RM label="DRAWDOWN" value={`${s.maxDrawdown.toFixed(1)}%`}/><div className="holdBadge">{s.endingBalance>data.buyHoldEnding?'BEAT HOLD':'BELOW HOLD'}</div></div>)}</div></>}
 </section></main>;
}
function Metric({label,value}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>};function RM({label,value}){return <div className="rankMetric"><span>{label}</span><strong>{value}</strong></div>};
