'use client';
import {useState} from 'react';
export default function MonthTest(){
 const [data,setData]=useState(null),[status,setStatus]=useState('idle'),[error,setError]=useState(''),[days,setDays]=useState(30);
 async function run(d=days){setDays(d);setStatus('loading');setError('');try{const r=await fetch(`/api/month-test?days=${d}`,{cache:'no-store'});const text=await r.text();let x;try{x=JSON.parse(text);}catch{throw new Error(text?.slice(0,180)||`Server returned ${r.status}`);}if(!r.ok||x.error)throw new Error(x.error||'Historical test failed');setData(x);setStatus('done');}catch(e){setError(e.message||'Historical test failed');setStatus('error');}}
 return <main><header><div><span className="eyebrow">HISTORICAL LAB</span><h1>BTC Strategy Championship</h1><p>Replay frozen strategies over longer BTC history without reoptimizing them.</p></div><a className="live" href="/optimizer">Back to optimizer</a></header>
 <section className="panel" style={{marginTop:32}}><div className="panelHead"><div><span className="eyebrow">$100 START</span><h2>Does the strategy survive longer periods?</h2></div><div style={{display:'flex',gap:10}}><button onClick={()=>run(30)} disabled={status==='loading'}>30 days</button><button onClick={()=>run(90)} disabled={status==='loading'}>90 days</button></div></div>
 <p className="panelCopy">History now comes from Binance.US five minute BTC candles, then gets combined into the same 15 minute and 30 minute bars used by the strategies. Every test keeps the simulated 0.6% transaction fee.</p>
 {status==='idle'&&<div className="empty">Choose 30 days first. If that works, run the same frozen strategies across 90 days.</div>}
 {status==='loading'&&<div className="empty">Downloading {days} days of BTC history and replaying the strategies. This can take a little while.</div>}
 {status==='error'&&<div className="empty errorText">Historical test could not finish: {error}</div>}
 {data&&<><div className="benchmarkRow"><Metric label="SOURCE" value={`${data.source} ${data.symbol}`}/><Metric label="5 MIN CANDLES" value={data.candles.toLocaleString()}/><Metric label="BUY AND HOLD" value={`$${data.buyHoldEnding.toFixed(2)}`}/><Metric label="HOLD RETURN" value={`${data.buyHoldReturnPct>=0?'+':''}${data.buyHoldReturnPct.toFixed(2)}%`}/></div>
 <div className="backtestSummary"><strong>Best {data.days} day bot: {data.best.name} at ${data.best.endingBalance.toFixed(2)}</strong><span>{data.best.endingBalance>data.buyHoldEnding?'It beat buy and hold in this historical window.':'Buy and hold still beat the best tested bot in this historical window.'}</span></div>
 <div className="rankList">{data.results.map((s,i)=><div className={`rankRow ${s.endingBalance>data.buyHoldEnding?'beatHold':''}`} key={s.name}><div className="rankNum">#{i+1}</div><div className="rankName"><strong>{s.name}: {s.minutes} minute EMA {s.fast}/{s.slow}</strong><span>Confirm {(s.confirm*100).toFixed(2)}%, min profit {(s.minProfit*100).toFixed(2)}%, stop {(s.stop*100).toFixed(2)}%.</span></div><RM label="ENDING" value={`$${s.endingBalance.toFixed(2)}`}/><RM label="RETURN" value={`${s.returnPct>=0?'+':''}${s.returnPct.toFixed(2)}%`}/><RM label="TRADES" value={String(s.trades)}/><RM label="FEES" value={`$${s.fees.toFixed(2)}`}/><RM label="WIN RATE" value={`${s.winRate.toFixed(1)}%`}/><RM label="DRAWDOWN" value={`${s.maxDrawdown.toFixed(1)}%`}/><div className="holdBadge">{s.endingBalance>data.buyHoldEnding?'BEAT HOLD':'BELOW HOLD'}</div></div>)}</div></>}
 </section></main>;
}
function Metric({label,value}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>};function RM({label,value}){return <div className="rankMetric"><span>{label}</span><strong>{value}</strong></div>};
